// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-judge-system/pkg/config"
	"go-judge-system/pkg/database"
	"go-judge-system/pkg/logger"
	"go-judge-system/services/submission/internal/adapter/inbound/http"
	"go-judge-system/services/submission/internal/adapter/inbound/http/handler"
	submission2 "go-judge-system/services/submission/internal/adapter/inbound/http/handler/submission"
	"go-judge-system/services/submission/internal/adapter/inbound/http/middleware"
	"go-judge-system/services/submission/internal/adapter/outbound/judge"
	"go-judge-system/services/submission/internal/adapter/outbound/persistence/postgres"
	"go-judge-system/services/submission/internal/adapter/outbound/problem"
	"go-judge-system/services/submission/internal/application/usecase/submission"
	"go-judge-system/services/submission/internal/container"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*container.App, error) {
	databaseConfig := cfg.Database
	db, err := database.ConnectDatabase(databaseConfig)
	if err != nil {
		return nil, err
	}
	submissionRepository := postgres.NewSubmissionRepository(db)
	loggerConfig := cfg.Logger
	serverConfig := cfg.Server
	string2 := provideServerMode(serverConfig)
	zapLogger := logger.NewLogger(loggerConfig, string2)
	judgePublisher := judge.NewNoopJudgePublisher(zapLogger)
	createSubmissionUseCase := submission.NewCreateSubmissionUseCase(submissionRepository, judgePublisher, zapLogger)
	createSubmissionHandler := submission2.NewCreateSubmissionHandler(createSubmissionUseCase)
	listSubmissionsUseCase := submission.NewListSubmissionsUseCase(submissionRepository, zapLogger)
	listSubmissionsHandler := submission2.NewListSubmissionsHandler(listSubmissionsUseCase)
	submissionResultRepository := postgres.NewSubmissionResultRepository(db)
	problemAccessChecker := problem.NewProblemAccessChecker()
	getSubmissionUseCase := submission.NewGetSubmissionUseCase(submissionRepository, submissionResultRepository, problemAccessChecker, zapLogger)
	getSubmissionHandler := submission2.NewGetSubmissionHandler(getSubmissionUseCase)
	rejudgeSubmissionUseCase := submission.NewRejudgeSubmissionUseCase(submissionRepository, submissionResultRepository, problemAccessChecker, judgePublisher, zapLogger)
	rejudgeSubmissionHandler := submission2.NewRejudgeSubmissionHandler(rejudgeSubmissionUseCase)
	submissionHandler := handler.NewSubmissionHandler(createSubmissionHandler, listSubmissionsHandler, getSubmissionHandler, rejudgeSubmissionHandler)
	handlerFunc := middleware.NewAuthMiddleware()
	router := http.NewRouter(submissionHandler, handlerFunc)
	app := container.NewApp(cfg, db, router, zapLogger)
	return app, nil
}

// wire.go:

func provideServerMode(cfg config.ServerConfig) string {
	return cfg.Mode
}
