// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-judge-system/pkg/config"
	"go-judge-system/pkg/database"
	"go-judge-system/pkg/logger"
	"go-judge-system/services/submission/internal/adapter/inbound/http"
	"go-judge-system/services/submission/internal/adapter/inbound/http/middleware"
	"go-judge-system/services/submission/internal/container"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*container.App, error) {
	databaseConfig := cfg.Database
	db, err := database.ConnectDatabase(databaseConfig)
	if err != nil {
		return nil, err
	}
	handlerFunc := middleware.NewAuthMiddleware()
	router := http.NewRouter(handlerFunc)
	loggerConfig := cfg.Logger
	serverConfig := cfg.Server
	string2 := provideServerMode(serverConfig)
	zapLogger := logger.NewLogger(loggerConfig, string2)
	app := container.NewApp(cfg, db, router, zapLogger)
	return app, nil
}

// wire.go:

func provideServerMode(cfg config.ServerConfig) string {
	return cfg.Mode
}
