// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-judge-system/pkg/auth"
	"go-judge-system/pkg/cache"
	"go-judge-system/pkg/config"
	"go-judge-system/pkg/database"
	"go-judge-system/pkg/kafka"
	"go-judge-system/pkg/logger"
	"go-judge-system/pkg/middleware"
	"go-judge-system/services/submission/internal/adapter/inbound/http"
	"go-judge-system/services/submission/internal/adapter/inbound/http/handler"
	admin2 "go-judge-system/services/submission/internal/adapter/inbound/http/handler/admin"
	user2 "go-judge-system/services/submission/internal/adapter/inbound/http/handler/user"
	kafka2 "go-judge-system/services/submission/internal/adapter/inbound/kafka"
	"go-judge-system/services/submission/internal/adapter/outbound/id"
	"go-judge-system/services/submission/internal/adapter/outbound/judge"
	"go-judge-system/services/submission/internal/adapter/outbound/outbox"
	"go-judge-system/services/submission/internal/adapter/outbound/persistence/postgres"
	"go-judge-system/services/submission/internal/adapter/outbound/problem"
	"go-judge-system/services/submission/internal/adapter/outbound/stream"
	"go-judge-system/services/submission/internal/application/usecase/admin"
	"go-judge-system/services/submission/internal/application/usecase/result"
	"go-judge-system/services/submission/internal/application/usecase/user"
	"go-judge-system/services/submission/internal/container"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*container.App, error) {
	databaseConfig := cfg.Database
	db, err := database.ConnectDatabase(databaseConfig)
	if err != nil {
		return nil, err
	}
	submissionRepository := postgres.NewSubmissionRepository(db)
	transactionManager := postgres.NewTransactionManager(db)
	outboxRepository := postgres.NewOutboxRepository(db)
	kafkaConfig := cfg.Kafka
	judgePublisher := judge.NewOutboxJudgePublisher(outboxRepository, kafkaConfig)
	attemptIDGenerator := id.NewUUIDAttemptIDGenerator()
	problemGRPCConfig, err := container.ProvideProblemGRPCConfig(cfg)
	if err != nil {
		return nil, err
	}
	clientConn, err := container.ProvideProblemClientConn(problemGRPCConfig)
	if err != nil {
		return nil, err
	}
	problemServiceClient := container.ProvideProblemServiceClient(clientConn)
	duration := container.ProvideProblemGRPCTimeout(problemGRPCConfig)
	problemReader := problem.NewGRPCProblemReader(problemServiceClient, duration)
	createSubmissionUseCase := user.NewCreateSubmissionUseCase(submissionRepository, transactionManager, judgePublisher, attemptIDGenerator, problemReader)
	createSubmissionHandler := user2.NewCreateSubmissionHandler(createSubmissionUseCase)
	judgeGRPCConfig, err := container.ProvideJudgeGRPCConfig(cfg)
	if err != nil {
		return nil, err
	}
	judgeClientConn, err := container.ProvideJudgeClientConn(judgeGRPCConfig)
	if err != nil {
		return nil, err
	}
	judgeServiceClient := container.ProvideJudgeServiceClient(judgeClientConn)
	judgeRunner := judge.NewGRPCRunner(judgeServiceClient)
	runCodeLimits := container.ProvideRunCodeLimits(cfg)
	runCodeUseCase := user.NewRunCodeUseCase(problemReader, judgeRunner, runCodeLimits)
	runCodeHandler := user2.NewRunCodeHandler(runCodeUseCase)
	getSubmissionUseCase := user.NewGetSubmissionUseCase(submissionRepository)
	getSubmissionHandler := user2.NewGetSubmissionHandler(getSubmissionUseCase)
	listMySubmissionsUseCase := user.NewListMySubmissionsUseCase(submissionRepository)
	listMySubmissionsHandler := user2.NewListMySubmissionsHandler(listMySubmissionsUseCase)
	submissionStreamSnapshotRepository := postgres.NewSubmissionStreamSnapshotRepository(db)
	sseConfig, err := container.ProvideSSEConfig(cfg)
	if err != nil {
		return nil, err
	}
	submissionStreamTicketService := stream.NewHMACSubmissionStreamTicketService(sseConfig)
	issueSubmissionStreamTicketUseCase := user.NewIssueSubmissionStreamTicketUseCase(submissionStreamSnapshotRepository, submissionStreamTicketService)
	issueSubmissionStreamTicketHandler := user2.NewIssueSubmissionStreamTicketHandler(issueSubmissionStreamTicketUseCase)
	submissionEventHub := stream.NewSubmissionEventHub()
	loggerConfig := cfg.Logger
	serverConfig := cfg.Server
	string2 := provideServerMode(serverConfig)
	zapLogger := logger.NewLogger(loggerConfig, string2)
	submissionEventsHandler := user2.NewSubmissionEventsHandler(submissionStreamSnapshotRepository, submissionStreamTicketService, submissionEventHub, sseConfig, zapLogger)
	userHandler := handler.NewUserHandler(createSubmissionHandler, runCodeHandler, getSubmissionHandler, listMySubmissionsHandler, issueSubmissionStreamTicketHandler, submissionEventsHandler)
	listAdminSubmissionsUseCase := admin.NewListAdminSubmissionsUseCase(submissionRepository)
	listSubmissionsHandler := admin2.NewListSubmissionsHandler(listAdminSubmissionsUseCase)
	adminHandler := handler.NewAdminHandler(listSubmissionsHandler)
	redisConfig := cfg.Redis
	client, err := cache.ConnectRedis(redisConfig)
	if err != nil {
		return nil, err
	}
	jwtConfig := cfg.JWT
	logoutAllIATStore := auth.NewRedisLogoutAllIATStore(client, jwtConfig)
	handlerFunc := middleware.NewAuthMiddleware(logoutAllIATStore)
	router := http.NewRouter(userHandler, adminHandler, handlerFunc, zapLogger)
	syncProducer, err := kafka.NewSyncProducer(kafkaConfig, zapLogger)
	if err != nil {
		return nil, err
	}
	outboxRelay := outbox.NewOutboxRelay(outboxRepository, syncProducer, zapLogger)
	consumerGroup, err := kafka.NewConsumerGroup(kafkaConfig, zapLogger)
	if err != nil {
		return nil, err
	}
	submissionResultRepository := postgres.NewSubmissionResultRepository(db)
	applyJudgeResultUseCase := result.NewApplyJudgeResultUseCase(submissionRepository, submissionResultRepository, transactionManager)
	dltPublisher := kafka2.NewDLTPublisher(syncProducer, kafkaConfig, zapLogger)
	judgeResultConsumer := kafka2.NewJudgeResultConsumer(consumerGroup, kafkaConfig, applyJudgeResultUseCase, dltPublisher, zapLogger)
	app := container.NewApp(cfg, db, router, outboxRelay, judgeResultConsumer, zapLogger, syncProducer, consumerGroup, clientConn, judgeClientConn)
	return app, nil
}

// wire.go:

func provideServerMode(cfg config.ServerConfig) string {
	return cfg.Mode
}
