version: '3.8'

services:
  gateway:
    container_name: judge_gateway
    image: devopsfaith/krakend:2.6.0
    ports:
      - "8080:8080"
    volumes:
      - ./gateway/krakend.json:/etc/krakend/krakend.json:ro
      - ./gateway/symmetric.json:/etc/krakend/symmetric.json:ro
    networks:
      - judge_net
    depends_on:
      - auth-service

  postgres:
    container_name: judge_postgres
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - ./environment/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - judge_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d auth_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    container_name: judge_redis
    image: redis:7-alpine
    restart: unless-stopped
    env_file:
      - ./environment/redis.env
    ports:
      - "6379:6379"
    command: >
      /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    networks:
      - judge_net
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a $$REDIS_PASSWORD ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
  mailhog:
    container_name: judge_mailhog
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - judge_net

  auth-service:
    container_name: judge_auth
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    env_file:
      - ./environment/service.env
    user: "1000:1000"
    volumes:
      - ./services/auth/config:/app/config:ro
      - ./services/auth/logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - judge_net

networks:
  judge_net:


volumes:
  postgres_data:
