// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-judge-system/pkg/config"
	"go-judge-system/pkg/database"
	"go-judge-system/pkg/logger"
	"go-judge-system/pkg/minio"
	"go-judge-system/services/problem/internal/adapter/inbound/http"
	"go-judge-system/services/problem/internal/adapter/inbound/http/handler"
	problem2 "go-judge-system/services/problem/internal/adapter/inbound/http/handler/problem"
	testcase2 "go-judge-system/services/problem/internal/adapter/inbound/http/handler/test_case"
	"go-judge-system/services/problem/internal/adapter/inbound/http/middleware"
	"go-judge-system/services/problem/internal/adapter/outbound/persistence/postgres"
	minio2 "go-judge-system/services/problem/internal/adapter/outbound/storage/minio"
	"go-judge-system/services/problem/internal/application/usecase/problem"
	"go-judge-system/services/problem/internal/application/usecase/test_case"
	"go-judge-system/services/problem/internal/container"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*container.App, error) {
	databaseConfig := cfg.Database
	db, err := database.ConnectDatabase(databaseConfig)
	if err != nil {
		return nil, err
	}
	problemRepository := postgres.NewProblemRepository(db)
	loggerConfig := cfg.Logger
	serverConfig := cfg.Server
	string2 := provideServerMode(serverConfig)
	zapLogger := logger.NewLogger(loggerConfig, string2)
	createProblemUseCase := problem.NewCreateProblemUseCase(problemRepository, zapLogger)
	createProblemHandler := problem2.NewCreateProblemHandler(createProblemUseCase)
	updateProblemUseCase := problem.NewUpdateProblemUseCase(problemRepository, zapLogger)
	updateProblemHandler := problem2.NewUpdateProblemHandler(updateProblemUseCase)
	deleteProblemUseCase := problem.NewDeleteProblemUseCase(problemRepository, zapLogger)
	deleteProblemHandler := problem2.NewDeleteProblemHandler(deleteProblemUseCase)
	getProblemUseCase := problem.NewGetProblemUseCase(problemRepository, zapLogger)
	getProblemHandler := problem2.NewGetProblemHandler(getProblemUseCase)
	listProblemsUseCase := problem.NewListProblemsUseCase(problemRepository, zapLogger)
	listProblemsHandler := problem2.NewListProblemsHandler(listProblemsUseCase)
	publishProblemUseCase := problem.NewPublishProblemUseCase(problemRepository, zapLogger)
	publishProblemHandler := problem2.NewPublishProblemHandler(publishProblemUseCase)
	hideProblemUseCase := problem.NewHideProblemUseCase(problemRepository, zapLogger)
	hideProblemHandler := problem2.NewHideProblemHandler(hideProblemUseCase)
	problemHandler := handler.NewProblemHandler(createProblemHandler, updateProblemHandler, deleteProblemHandler, getProblemHandler, listProblemsHandler, publishProblemHandler, hideProblemHandler)
	testCaseRepository := postgres.NewTestCaseRepository(db)
	minIOConfig := &cfg.MinIO
	client, err := minio.NewMinioClient(minIOConfig)
	if err != nil {
		return nil, err
	}
	configMinIOConfig := cfg.MinIO
	objectStorage := minio2.NewMinioStorage(client, configMinIOConfig)
	uploadTestCaseUseCase := testcase.NewUploadTestCaseUseCase(problemRepository, testCaseRepository, objectStorage, zapLogger)
	uploadTestCaseHandler := testcase2.NewUploadTestCaseHandler(uploadTestCaseUseCase)
	testCaseHandler := handler.NewTestCaseHandler(uploadTestCaseHandler)
	handlerFunc := middleware.NewAuthMiddleware()
	router := http.NewRouter(problemHandler, testCaseHandler, handlerFunc)
	app := container.NewApp(cfg, router, zapLogger)
	return app, nil
}

// wire.go:

func provideServerMode(cfg config.ServerConfig) string {
	return cfg.Mode
}
