// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-judge-system/pkg/config"
	"go-judge-system/pkg/kafka"
	"go-judge-system/pkg/logger"
	"go-judge-system/workers/judge/internal/adapter/inbound/grpc"
	"go-judge-system/workers/judge/internal/adapter/inbound/grpc/handler"
	kafka2 "go-judge-system/workers/judge/internal/adapter/inbound/kafka"
	"go-judge-system/workers/judge/internal/adapter/outbound/judge"
	"go-judge-system/workers/judge/internal/adapter/outbound/problem"
	"go-judge-system/workers/judge/internal/adapter/outbound/testcase"
	judge2 "go-judge-system/workers/judge/internal/application/usecase/judge"
	"go-judge-system/workers/judge/internal/container"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*container.App, func(), error) {
	kafkaConfig := container.ProvideKafkaConfig(cfg)
	loggerConfig := container.ProvideLoggerConfig(cfg)
	string2 := container.ProvideServiceName()
	zapLogger := logger.NewLogger(loggerConfig, string2)
	consumerGroup, err := kafka.NewConsumerGroup(kafkaConfig, zapLogger)
	if err != nil {
		return nil, nil, err
	}
	sandboxServiceURL := container.ProvideSandboxServiceURL()
	goJudgeClient := container.ProvideGoJudgeClient(sandboxServiceURL, zapLogger)
	syncProducer, err := kafka.NewSyncProducer(kafkaConfig, zapLogger)
	if err != nil {
		return nil, nil, err
	}
	kafkaResultPublisher := judge.NewKafkaResultPublisher(syncProducer, kafkaConfig, zapLogger)
	problemGRPCConfig, err := container.ProvideProblemGRPCConfig(cfg)
	if err != nil {
		return nil, nil, err
	}
	clientConn, err := container.ProvideProblemClientConn(problemGRPCConfig)
	if err != nil {
		return nil, nil, err
	}
	problemServiceClient := container.ProvideProblemServiceClient(clientConn)
	duration := container.ProvideProblemGRPCTimeout(problemGRPCConfig)
	grpcMetadataReader := problem.NewGRPCMetadataReader(problemServiceClient, duration, zapLogger)
	officialLoader := testcase.NewOfficialLoader(zapLogger)
	processJudgeJobUseCase := judge2.NewProcessJudgeJobUseCase(goJudgeClient, kafkaResultPublisher, grpcMetadataReader, officialLoader, zapLogger)
	dltPublisher := kafka2.NewDLTPublisher(syncProducer, kafkaConfig, zapLogger)
	judgeJobConsumer := kafka2.NewJudgeJobConsumer(consumerGroup, kafkaConfig, processJudgeJobUseCase, dltPublisher, zapLogger)
	serverConfig := cfg.Server
	runCodeUseCase := judge2.NewRunCodeUseCase(goJudgeClient)
	runCodeHandler := handler.NewRunCodeHandler(runCodeUseCase)
	judgeServer := grpc.NewJudgeServer(runCodeHandler)
	server := grpc.NewServer(serverConfig, judgeServer)
	app := container.NewApp(cfg, judgeJobConsumer, server, zapLogger, syncProducer, clientConn)
	return app, func() {
	}, nil
}
