// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-judge-system/pkg/config"
	"go-judge-system/pkg/kafka"
	"go-judge-system/pkg/logger"
	kafka2 "go-judge-system/workers/judge/internal/adapter/inbound/kafka"
	"go-judge-system/workers/judge/internal/adapter/outbound/execute"
	"go-judge-system/workers/judge/internal/adapter/outbound/judge"
	"go-judge-system/workers/judge/internal/adapter/outbound/problem"
	judge2 "go-judge-system/workers/judge/internal/application/usecase/judge"
	"go-judge-system/workers/judge/internal/container"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*container.App, func(), error) {
	kafkaConfig := container.ProvideKafkaConfig(cfg)
	loggerConfig := container.ProvideLoggerConfig(cfg)
	string2 := container.ProvideServiceName()
	zapLogger := logger.NewLogger(loggerConfig, string2)
	consumerGroup, err := kafka.NewConsumerGroup(kafkaConfig, zapLogger)
	if err != nil {
		return nil, nil, err
	}
	goJudgeClient := execute.NewGoJudgeClient(string2, zapLogger)
	syncProducer, err := kafka.NewSyncProducer(kafkaConfig, zapLogger)
	if err != nil {
		return nil, nil, err
	}
	kafkaResultPublisher := judge.NewKafkaResultPublisher(syncProducer, kafkaConfig, zapLogger)
	problemServiceClient := problem.NewProblemServiceClient(string2, zapLogger)
	processJudgeJobUseCase := judge2.NewProcessJudgeJobUseCase(goJudgeClient, kafkaResultPublisher, problemServiceClient, zapLogger)
	dltPublisher := kafka2.NewDLTPublisher(syncProducer, kafkaConfig, zapLogger)
	judgeJobConsumer := kafka2.NewJudgeJobConsumer(consumerGroup, kafkaConfig, processJudgeJobUseCase, dltPublisher, zapLogger)
	app := container.NewApp(cfg, judgeJobConsumer, zapLogger, syncProducer)
	return app, func() {
	}, nil
}
