// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/judge/v1/run.proto

package judgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunCodeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Language         string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	SourceCode       string                 `protobuf:"bytes,2,opt,name=source_code,json=sourceCode,proto3" json:"source_code,omitempty"`
	Testcases        []*RunTestCaseInput    `protobuf:"bytes,3,rep,name=testcases,proto3" json:"testcases,omitempty"`
	TimeLimitMs      int64                  `protobuf:"varint,4,opt,name=time_limit_ms,json=timeLimitMs,proto3" json:"time_limit_ms,omitempty"`
	MemoryLimitKb    int64                  `protobuf:"varint,5,opt,name=memory_limit_kb,json=memoryLimitKb,proto3" json:"memory_limit_kb,omitempty"`
	OutputLimitBytes int64                  `protobuf:"varint,6,opt,name=output_limit_bytes,json=outputLimitBytes,proto3" json:"output_limit_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RunCodeRequest) Reset() {
	*x = RunCodeRequest{}
	mi := &file_proto_judge_v1_run_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCodeRequest) ProtoMessage() {}

func (x *RunCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_judge_v1_run_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCodeRequest.ProtoReflect.Descriptor instead.
func (*RunCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_judge_v1_run_proto_rawDescGZIP(), []int{0}
}

func (x *RunCodeRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *RunCodeRequest) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

func (x *RunCodeRequest) GetTestcases() []*RunTestCaseInput {
	if x != nil {
		return x.Testcases
	}
	return nil
}

func (x *RunCodeRequest) GetTimeLimitMs() int64 {
	if x != nil {
		return x.TimeLimitMs
	}
	return 0
}

func (x *RunCodeRequest) GetMemoryLimitKb() int64 {
	if x != nil {
		return x.MemoryLimitKb
	}
	return 0
}

func (x *RunCodeRequest) GetOutputLimitBytes() int64 {
	if x != nil {
		return x.OutputLimitBytes
	}
	return 0
}

type RunTestCaseInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind           string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Stdin          string                 `protobuf:"bytes,3,opt,name=stdin,proto3" json:"stdin,omitempty"`
	ExpectedOutput *string                `protobuf:"bytes,4,opt,name=expected_output,json=expectedOutput,proto3,oneof" json:"expected_output,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RunTestCaseInput) Reset() {
	*x = RunTestCaseInput{}
	mi := &file_proto_judge_v1_run_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTestCaseInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTestCaseInput) ProtoMessage() {}

func (x *RunTestCaseInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_judge_v1_run_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTestCaseInput.ProtoReflect.Descriptor instead.
func (*RunTestCaseInput) Descriptor() ([]byte, []int) {
	return file_proto_judge_v1_run_proto_rawDescGZIP(), []int{1}
}

func (x *RunTestCaseInput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RunTestCaseInput) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *RunTestCaseInput) GetStdin() string {
	if x != nil {
		return x.Stdin
	}
	return ""
}

func (x *RunTestCaseInput) GetExpectedOutput() string {
	if x != nil && x.ExpectedOutput != nil {
		return *x.ExpectedOutput
	}
	return ""
}

type RunCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CompileOutput string                 `protobuf:"bytes,2,opt,name=compile_output,json=compileOutput,proto3" json:"compile_output,omitempty"`
	Tests         []*RunTestCaseResult   `protobuf:"bytes,3,rep,name=tests,proto3" json:"tests,omitempty"`
	Diagnostics   []*CodeDiagnostic      `protobuf:"bytes,4,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCodeResponse) Reset() {
	*x = RunCodeResponse{}
	mi := &file_proto_judge_v1_run_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCodeResponse) ProtoMessage() {}

func (x *RunCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_judge_v1_run_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCodeResponse.ProtoReflect.Descriptor instead.
func (*RunCodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_judge_v1_run_proto_rawDescGZIP(), []int{2}
}

func (x *RunCodeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RunCodeResponse) GetCompileOutput() string {
	if x != nil {
		return x.CompileOutput
	}
	return ""
}

func (x *RunCodeResponse) GetTests() []*RunTestCaseResult {
	if x != nil {
		return x.Tests
	}
	return nil
}

func (x *RunCodeResponse) GetDiagnostics() []*CodeDiagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type RunTestCaseResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind            string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Stdout          string                 `protobuf:"bytes,4,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr          string                 `protobuf:"bytes,5,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExpectedOutput  *string                `protobuf:"bytes,6,opt,name=expected_output,json=expectedOutput,proto3,oneof" json:"expected_output,omitempty"`
	ExecutionTimeMs int64                  `protobuf:"varint,7,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	MemoryUsedKb    int64                  `protobuf:"varint,8,opt,name=memory_used_kb,json=memoryUsedKb,proto3" json:"memory_used_kb,omitempty"`
	Diagnostics     []*CodeDiagnostic      `protobuf:"bytes,9,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RunTestCaseResult) Reset() {
	*x = RunTestCaseResult{}
	mi := &file_proto_judge_v1_run_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTestCaseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTestCaseResult) ProtoMessage() {}

func (x *RunTestCaseResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_judge_v1_run_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTestCaseResult.ProtoReflect.Descriptor instead.
func (*RunTestCaseResult) Descriptor() ([]byte, []int) {
	return file_proto_judge_v1_run_proto_rawDescGZIP(), []int{3}
}

func (x *RunTestCaseResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RunTestCaseResult) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *RunTestCaseResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RunTestCaseResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *RunTestCaseResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *RunTestCaseResult) GetExpectedOutput() string {
	if x != nil && x.ExpectedOutput != nil {
		return *x.ExpectedOutput
	}
	return ""
}

func (x *RunTestCaseResult) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *RunTestCaseResult) GetMemoryUsedKb() int64 {
	if x != nil {
		return x.MemoryUsedKb
	}
	return 0
}

func (x *RunTestCaseResult) GetDiagnostics() []*CodeDiagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type CodeDiagnostic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Line          int32                  `protobuf:"varint,4,opt,name=line,proto3" json:"line,omitempty"`
	Column        int32                  `protobuf:"varint,5,opt,name=column,proto3" json:"column,omitempty"`
	EndLine       *int32                 `protobuf:"varint,6,opt,name=end_line,json=endLine,proto3,oneof" json:"end_line,omitempty"`
	EndColumn     *int32                 `protobuf:"varint,7,opt,name=end_column,json=endColumn,proto3,oneof" json:"end_column,omitempty"`
	TestcaseId    *string                `protobuf:"bytes,8,opt,name=testcase_id,json=testcaseId,proto3,oneof" json:"testcase_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeDiagnostic) Reset() {
	*x = CodeDiagnostic{}
	mi := &file_proto_judge_v1_run_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeDiagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeDiagnostic) ProtoMessage() {}

func (x *CodeDiagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_judge_v1_run_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeDiagnostic.ProtoReflect.Descriptor instead.
func (*CodeDiagnostic) Descriptor() ([]byte, []int) {
	return file_proto_judge_v1_run_proto_rawDescGZIP(), []int{4}
}

func (x *CodeDiagnostic) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CodeDiagnostic) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *CodeDiagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CodeDiagnostic) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *CodeDiagnostic) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *CodeDiagnostic) GetEndLine() int32 {
	if x != nil && x.EndLine != nil {
		return *x.EndLine
	}
	return 0
}

func (x *CodeDiagnostic) GetEndColumn() int32 {
	if x != nil && x.EndColumn != nil {
		return *x.EndColumn
	}
	return 0
}

func (x *CodeDiagnostic) GetTestcaseId() string {
	if x != nil && x.TestcaseId != nil {
		return *x.TestcaseId
	}
	return ""
}

var File_proto_judge_v1_run_proto protoreflect.FileDescriptor

const file_proto_judge_v1_run_proto_rawDesc = "" +
	"\n" +
	"\x18proto/judge/v1/run.proto\x12\bjudge.v1\"\x81\x02\n" +
	"\x0eRunCodeRequest\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x1f\n" +
	"\vsource_code\x18\x02 \x01(\tR\n" +
	"sourceCode\x128\n" +
	"\ttestcases\x18\x03 \x03(\v2\x1a.judge.v1.RunTestCaseInputR\ttestcases\x12\"\n" +
	"\rtime_limit_ms\x18\x04 \x01(\x03R\vtimeLimitMs\x12&\n" +
	"\x0fmemory_limit_kb\x18\x05 \x01(\x03R\rmemoryLimitKb\x12,\n" +
	"\x12output_limit_bytes\x18\x06 \x01(\x03R\x10outputLimitBytes\"\x8e\x01\n" +
	"\x10RunTestCaseInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05stdin\x18\x03 \x01(\tR\x05stdin\x12,\n" +
	"\x0fexpected_output\x18\x04 \x01(\tH\x00R\x0eexpectedOutput\x88\x01\x01B\x12\n" +
	"\x10_expected_output\"\xbf\x01\n" +
	"\x0fRunCodeResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12%\n" +
	"\x0ecompile_output\x18\x02 \x01(\tR\rcompileOutput\x121\n" +
	"\x05tests\x18\x03 \x03(\v2\x1b.judge.v1.RunTestCaseResultR\x05tests\x12:\n" +
	"\vdiagnostics\x18\x04 \x03(\v2\x18.judge.v1.CodeDiagnosticR\vdiagnostics\"\xcf\x02\n" +
	"\x11RunTestCaseResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06stdout\x18\x04 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x05 \x01(\tR\x06stderr\x12,\n" +
	"\x0fexpected_output\x18\x06 \x01(\tH\x00R\x0eexpectedOutput\x88\x01\x01\x12*\n" +
	"\x11execution_time_ms\x18\a \x01(\x03R\x0fexecutionTimeMs\x12$\n" +
	"\x0ememory_used_kb\x18\b \x01(\x03R\fmemoryUsedKb\x12:\n" +
	"\vdiagnostics\x18\t \x03(\v2\x18.judge.v1.CodeDiagnosticR\vdiagnosticsB\x12\n" +
	"\x10_expected_output\"\x9c\x02\n" +
	"\x0eCodeDiagnostic\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x12\n" +
	"\x04line\x18\x04 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x05 \x01(\x05R\x06column\x12\x1e\n" +
	"\bend_line\x18\x06 \x01(\x05H\x00R\aendLine\x88\x01\x01\x12\"\n" +
	"\n" +
	"end_column\x18\a \x01(\x05H\x01R\tendColumn\x88\x01\x01\x12$\n" +
	"\vtestcase_id\x18\b \x01(\tH\x02R\n" +
	"testcaseId\x88\x01\x01B\v\n" +
	"\t_end_lineB\r\n" +
	"\v_end_columnB\x0e\n" +
	"\f_testcase_id2N\n" +
	"\fJudgeService\x12>\n" +
	"\aRunCode\x12\x18.judge.v1.RunCodeRequest\x1a\x19.judge.v1.RunCodeResponseB)Z'go-judge-system/pkg/pb/judge/v1;judgev1b\x06proto3"

var (
	file_proto_judge_v1_run_proto_rawDescOnce sync.Once
	file_proto_judge_v1_run_proto_rawDescData []byte
)

func file_proto_judge_v1_run_proto_rawDescGZIP() []byte {
	file_proto_judge_v1_run_proto_rawDescOnce.Do(func() {
		file_proto_judge_v1_run_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_judge_v1_run_proto_rawDesc), len(file_proto_judge_v1_run_proto_rawDesc)))
	})
	return file_proto_judge_v1_run_proto_rawDescData
}

var file_proto_judge_v1_run_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_judge_v1_run_proto_goTypes = []any{
	(*RunCodeRequest)(nil),    // 0: judge.v1.RunCodeRequest
	(*RunTestCaseInput)(nil),  // 1: judge.v1.RunTestCaseInput
	(*RunCodeResponse)(nil),   // 2: judge.v1.RunCodeResponse
	(*RunTestCaseResult)(nil), // 3: judge.v1.RunTestCaseResult
	(*CodeDiagnostic)(nil),    // 4: judge.v1.CodeDiagnostic
}
var file_proto_judge_v1_run_proto_depIdxs = []int32{
	1, // 0: judge.v1.RunCodeRequest.testcases:type_name -> judge.v1.RunTestCaseInput
	3, // 1: judge.v1.RunCodeResponse.tests:type_name -> judge.v1.RunTestCaseResult
	4, // 2: judge.v1.RunCodeResponse.diagnostics:type_name -> judge.v1.CodeDiagnostic
	4, // 3: judge.v1.RunTestCaseResult.diagnostics:type_name -> judge.v1.CodeDiagnostic
	0, // 4: judge.v1.JudgeService.RunCode:input_type -> judge.v1.RunCodeRequest
	2, // 5: judge.v1.JudgeService.RunCode:output_type -> judge.v1.RunCodeResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_judge_v1_run_proto_init() }
func file_proto_judge_v1_run_proto_init() {
	if File_proto_judge_v1_run_proto != nil {
		return
	}
	file_proto_judge_v1_run_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_judge_v1_run_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_judge_v1_run_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_judge_v1_run_proto_rawDesc), len(file_proto_judge_v1_run_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_judge_v1_run_proto_goTypes,
		DependencyIndexes: file_proto_judge_v1_run_proto_depIdxs,
		MessageInfos:      file_proto_judge_v1_run_proto_msgTypes,
	}.Build()
	File_proto_judge_v1_run_proto = out.File
	file_proto_judge_v1_run_proto_goTypes = nil
	file_proto_judge_v1_run_proto_depIdxs = nil
}
