// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/problem/v1/problem.proto

package problemv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTestCaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemId     int64                  `protobuf:"varint,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTestCaseRequest) Reset() {
	*x = GetTestCaseRequest{}
	mi := &file_proto_problem_v1_problem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTestCaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestCaseRequest) ProtoMessage() {}

func (x *GetTestCaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_problem_v1_problem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestCaseRequest.ProtoReflect.Descriptor instead.
func (*GetTestCaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_problem_v1_problem_proto_rawDescGZIP(), []int{0}
}

func (x *GetTestCaseRequest) GetProblemId() int64 {
	if x != nil {
		return x.ProblemId
	}
	return 0
}

type GetTestCaseResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ZipDownloadUrl string                 `protobuf:"bytes,1,opt,name=zip_download_url,json=zipDownloadUrl,proto3" json:"zip_download_url,omitempty"`
	TestCount      int32                  `protobuf:"varint,2,opt,name=test_count,json=testCount,proto3" json:"test_count,omitempty"`
	Version        int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTestCaseResponse) Reset() {
	*x = GetTestCaseResponse{}
	mi := &file_proto_problem_v1_problem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTestCaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestCaseResponse) ProtoMessage() {}

func (x *GetTestCaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_problem_v1_problem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestCaseResponse.ProtoReflect.Descriptor instead.
func (*GetTestCaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_problem_v1_problem_proto_rawDescGZIP(), []int{1}
}

func (x *GetTestCaseResponse) GetZipDownloadUrl() string {
	if x != nil {
		return x.ZipDownloadUrl
	}
	return ""
}

func (x *GetTestCaseResponse) GetTestCount() int32 {
	if x != nil {
		return x.TestCount
	}
	return 0
}

func (x *GetTestCaseResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetProblemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemId     int64                  `protobuf:"varint,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	ActorUserId   string                 `protobuf:"bytes,2,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	ActorRole     string                 `protobuf:"bytes,3,opt,name=actor_role,json=actorRole,proto3" json:"actor_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProblemRequest) Reset() {
	*x = GetProblemRequest{}
	mi := &file_proto_problem_v1_problem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProblemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProblemRequest) ProtoMessage() {}

func (x *GetProblemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_problem_v1_problem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProblemRequest.ProtoReflect.Descriptor instead.
func (*GetProblemRequest) Descriptor() ([]byte, []int) {
	return file_proto_problem_v1_problem_proto_rawDescGZIP(), []int{2}
}

func (x *GetProblemRequest) GetProblemId() int64 {
	if x != nil {
		return x.ProblemId
	}
	return 0
}

func (x *GetProblemRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *GetProblemRequest) GetActorRole() string {
	if x != nil {
		return x.ActorRole
	}
	return ""
}

type GetProblemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemId     int64                  `protobuf:"varint,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProblemResponse) Reset() {
	*x = GetProblemResponse{}
	mi := &file_proto_problem_v1_problem_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProblemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProblemResponse) ProtoMessage() {}

func (x *GetProblemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_problem_v1_problem_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProblemResponse.ProtoReflect.Descriptor instead.
func (*GetProblemResponse) Descriptor() ([]byte, []int) {
	return file_proto_problem_v1_problem_proto_rawDescGZIP(), []int{3}
}

func (x *GetProblemResponse) GetProblemId() int64 {
	if x != nil {
		return x.ProblemId
	}
	return 0
}

func (x *GetProblemResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetProblemResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

var File_proto_problem_v1_problem_proto protoreflect.FileDescriptor

const file_proto_problem_v1_problem_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/problem/v1/problem.proto\x12\n" +
	"problem.v1\"3\n" +
	"\x12GetTestCaseRequest\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x01 \x01(\x03R\tproblemId\"x\n" +
	"\x13GetTestCaseResponse\x12(\n" +
	"\x10zip_download_url\x18\x01 \x01(\tR\x0ezipDownloadUrl\x12\x1d\n" +
	"\n" +
	"test_count\x18\x02 \x01(\x05R\ttestCount\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\"u\n" +
	"\x11GetProblemRequest\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x01 \x01(\x03R\tproblemId\x12\"\n" +
	"\ractor_user_id\x18\x02 \x01(\tR\vactorUserId\x12\x1d\n" +
	"\n" +
	"actor_role\x18\x03 \x01(\tR\tactorRole\"]\n" +
	"\x12GetProblemResponse\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x01 \x01(\x03R\tproblemId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug2\xad\x01\n" +
	"\x0eProblemService\x12N\n" +
	"\vGetTestCase\x12\x1e.problem.v1.GetTestCaseRequest\x1a\x1f.problem.v1.GetTestCaseResponse\x12K\n" +
	"\n" +
	"GetProblem\x12\x1d.problem.v1.GetProblemRequest\x1a\x1e.problem.v1.GetProblemResponseB-Z+go-judge-system/pkg/pb/problem/v1;problemv1b\x06proto3"

var (
	file_proto_problem_v1_problem_proto_rawDescOnce sync.Once
	file_proto_problem_v1_problem_proto_rawDescData []byte
)

func file_proto_problem_v1_problem_proto_rawDescGZIP() []byte {
	file_proto_problem_v1_problem_proto_rawDescOnce.Do(func() {
		file_proto_problem_v1_problem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_problem_v1_problem_proto_rawDesc), len(file_proto_problem_v1_problem_proto_rawDesc)))
	})
	return file_proto_problem_v1_problem_proto_rawDescData
}

var file_proto_problem_v1_problem_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_problem_v1_problem_proto_goTypes = []any{
	(*GetTestCaseRequest)(nil),  // 0: problem.v1.GetTestCaseRequest
	(*GetTestCaseResponse)(nil), // 1: problem.v1.GetTestCaseResponse
	(*GetProblemRequest)(nil),   // 2: problem.v1.GetProblemRequest
	(*GetProblemResponse)(nil),  // 3: problem.v1.GetProblemResponse
}
var file_proto_problem_v1_problem_proto_depIdxs = []int32{
	0, // 0: problem.v1.ProblemService.GetTestCase:input_type -> problem.v1.GetTestCaseRequest
	2, // 1: problem.v1.ProblemService.GetProblem:input_type -> problem.v1.GetProblemRequest
	1, // 2: problem.v1.ProblemService.GetTestCase:output_type -> problem.v1.GetTestCaseResponse
	3, // 3: problem.v1.ProblemService.GetProblem:output_type -> problem.v1.GetProblemResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_problem_v1_problem_proto_init() }
func file_proto_problem_v1_problem_proto_init() {
	if File_proto_problem_v1_problem_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_problem_v1_problem_proto_rawDesc), len(file_proto_problem_v1_problem_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_problem_v1_problem_proto_goTypes,
		DependencyIndexes: file_proto_problem_v1_problem_proto_depIdxs,
		MessageInfos:      file_proto_problem_v1_problem_proto_msgTypes,
	}.Build()
	File_proto_problem_v1_problem_proto = out.File
	file_proto_problem_v1_problem_proto_goTypes = nil
	file_proto_problem_v1_problem_proto_depIdxs = nil
}
