// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-judge-system/pkg/cache"
	"go-judge-system/pkg/config"
	"go-judge-system/pkg/database"
	"go-judge-system/pkg/logger"
	"go-judge-system/services/auth/internal/adapter/inbound/http"
	"go-judge-system/services/auth/internal/adapter/inbound/http/handler"
	"go-judge-system/services/auth/internal/adapter/outbound/cache/redis"
	"go-judge-system/services/auth/internal/adapter/outbound/mail"
	"go-judge-system/services/auth/internal/adapter/outbound/persistence/postgres"
	"go-judge-system/services/auth/internal/application/usecase"
	"go-judge-system/services/auth/internal/container"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*container.App, error) {
	databaseConfig := cfg.Database
	db, err := database.ConnectDatabase(databaseConfig)
	if err != nil {
		return nil, err
	}
	userRepository := postgres.NewUserRepository(db)
	redisConfig := cfg.Redis
	client, err := cache.ConnectRedis(redisConfig)
	if err != nil {
		return nil, err
	}
	cacheRepository := redis.NewCacheRepository(client)
	smtpConfig := cfg.SMTP
	loggerConfig := cfg.Logger
	serverConfig := cfg.Server
	string2 := provideServerMode(serverConfig)
	zapLogger := logger.NewLogger(loggerConfig, string2)
	mailProvider := mail.NewSMTPProvider(smtpConfig, zapLogger)
	otpUseCase := usecase.NewOTPUseCase(cacheRepository, mailProvider, zapLogger)
	registerUseCase := usecase.NewRegisterUseCase(userRepository, otpUseCase, zapLogger)
	registerHandler := handler.NewRegisterHandler(registerUseCase)
	verifyOTPUseCase := usecase.NewVerifyOTPUseCase(otpUseCase, userRepository, zapLogger)
	verifyOTPHandler := handler.NewVerifyOTPHandler(verifyOTPUseCase)
	resendOTPUseCase := usecase.NewResendOTPUseCase(userRepository, otpUseCase, zapLogger)
	resendOTPHandler := handler.NewResendOTPHandler(resendOTPUseCase)
	authHandler := handler.NewAuthHandler(registerHandler, verifyOTPHandler, resendOTPHandler)
	router := http.NewRouter(authHandler)
	app := container.NewApp(cfg, router, zapLogger)
	return app, nil
}

// wire.go:

func provideServerMode(cfg config.ServerConfig) string {
	return cfg.Mode
}
