// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	auth3 "go-judge-system/pkg/auth"
	"go-judge-system/pkg/cache"
	"go-judge-system/pkg/config"
	"go-judge-system/pkg/database"
	"go-judge-system/pkg/logger"
	"go-judge-system/pkg/middleware"
	"go-judge-system/services/auth/internal/adapter/inbound/http"
	"go-judge-system/services/auth/internal/adapter/inbound/http/handler"
	admin2 "go-judge-system/services/auth/internal/adapter/inbound/http/handler/admin"
	auth2 "go-judge-system/services/auth/internal/adapter/inbound/http/handler/auth"
	user2 "go-judge-system/services/auth/internal/adapter/inbound/http/handler/user"
	"go-judge-system/services/auth/internal/adapter/outbound/cache/redis"
	"go-judge-system/services/auth/internal/adapter/outbound/crypto"
	"go-judge-system/services/auth/internal/adapter/outbound/jwt"
	"go-judge-system/services/auth/internal/adapter/outbound/mail"
	"go-judge-system/services/auth/internal/adapter/outbound/persistence/postgres"
	"go-judge-system/services/auth/internal/adapter/outbound/security"
	"go-judge-system/services/auth/internal/application/usecase/admin"
	"go-judge-system/services/auth/internal/application/usecase/auth"
	"go-judge-system/services/auth/internal/application/usecase/user"
	"go-judge-system/services/auth/internal/container"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*container.App, error) {
	databaseConfig := cfg.Database
	db, err := database.ConnectDatabase(databaseConfig)
	if err != nil {
		return nil, err
	}
	userRepository := postgres.NewUserRepository(db)
	smtpConfig := cfg.SMTP
	appConfig := cfg.App
	loggerConfig := cfg.Logger
	serverConfig := cfg.Server
	string2 := provideServerMode(serverConfig)
	zapLogger := logger.NewLogger(loggerConfig, string2)
	mailProvider := mail.NewSMTPProvider(smtpConfig, appConfig, zapLogger)
	tokenGenerator := crypto.NewTokenGenerator()
	redisConfig := cfg.Redis
	client, err := cache.ConnectRedis(redisConfig)
	if err != nil {
		return nil, err
	}
	tokenRepository := redis.NewTokenRepository(client)
	passwordEncoder := security.NewBcryptHasher()
	registerUseCase := auth.NewRegisterUseCase(userRepository, mailProvider, tokenGenerator, tokenRepository, passwordEncoder)
	registerHandler := auth2.NewRegisterHandler(registerUseCase)
	verifyEmailUseCase := auth.NewVerifyEmailUseCase(tokenGenerator, tokenRepository, userRepository)
	verifyEmailHandler := auth2.NewVerifyEmailHandler(verifyEmailUseCase)
	resendVerificationUseCase := auth.NewResendVerificationUseCase(userRepository, mailProvider, tokenGenerator, tokenRepository)
	resendVerificationHandler := auth2.NewResendVerificationHandler(resendVerificationUseCase)
	jwtConfig := cfg.JWT
	jwtProvider := jwt.NewJWTProvider(jwtConfig)
	loginUseCase := auth.NewLoginUseCase(userRepository, passwordEncoder, jwtProvider)
	loginHandler := auth2.NewLoginHandler(loginUseCase)
	logoutHandler := auth2.NewLogoutHandler()
	logoutAllIATStore := auth3.NewRedisLogoutAllIATStore(client, jwtConfig)
	logoutAllUseCase := auth.NewLogoutAllUseCase(logoutAllIATStore)
	logoutAllHandler := auth2.NewLogoutAllHandler(logoutAllUseCase)
	forgotPasswordUseCase := auth.NewForgotPasswordUseCase(userRepository, tokenRepository, tokenGenerator, mailProvider)
	forgotPasswordHandler := auth2.NewForgotPasswordHandler(forgotPasswordUseCase)
	resetPasswordUseCase := auth.NewResetPasswordUseCase(userRepository, tokenRepository, tokenGenerator, passwordEncoder)
	resetPasswordHandler := auth2.NewResetPasswordHandler(resetPasswordUseCase)
	changePasswordUseCase := auth.NewChangePasswordUseCase(userRepository, passwordEncoder)
	changePasswordHandler := auth2.NewChangePasswordHandler(changePasswordUseCase)
	refreshTokenUseCase := auth.NewRefreshTokenUseCase(jwtProvider, logoutAllIATStore)
	refreshTokenHandler := auth2.NewRefreshTokenHandler(refreshTokenUseCase)
	authHandler := handler.NewAuthHandler(registerHandler, verifyEmailHandler, resendVerificationHandler, loginHandler, logoutHandler, logoutAllHandler, forgotPasswordHandler, resetPasswordHandler, changePasswordHandler, refreshTokenHandler)
	getMeUseCase := user.NewGetMeUseCase(userRepository)
	getMeHandler := user2.NewGetMeHandler(getMeUseCase)
	getProfileUseCase := user.NewGetProfileUseCase(userRepository)
	getProfileHandler := user2.NewGetProfileHandler(getProfileUseCase)
	userHandler := handler.NewUserHandler(getMeHandler, getProfileHandler)
	assignRoleUseCase := admin.NewAssignRoleUseCase(userRepository)
	assignRoleHandler := admin2.NewAssignRoleHandler(assignRoleUseCase)
	adminHandler := handler.NewAdminHandler(assignRoleHandler)
	handlerFunc := middleware.NewAuthMiddleware(logoutAllIATStore)
	router := http.NewRouter(authHandler, userHandler, adminHandler, handlerFunc, zapLogger)
	app := container.NewApp(cfg, router, zapLogger)
	return app, nil
}

// wire.go:

func provideServerMode(cfg config.ServerConfig) string {
	return cfg.Mode
}
