// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-judge-system/pkg/cache"
	"go-judge-system/pkg/config"
	"go-judge-system/pkg/database"
	"go-judge-system/pkg/logger"
	"go-judge-system/services/auth/internal/adapter/inbound/http"
	"go-judge-system/services/auth/internal/adapter/inbound/http/handler"
	"go-judge-system/services/auth/internal/adapter/inbound/http/middleware"
	"go-judge-system/services/auth/internal/adapter/outbound/cache/redis"
	"go-judge-system/services/auth/internal/adapter/outbound/crypto"
	"go-judge-system/services/auth/internal/adapter/outbound/jwt"
	"go-judge-system/services/auth/internal/adapter/outbound/mail"
	"go-judge-system/services/auth/internal/adapter/outbound/otp"
	"go-judge-system/services/auth/internal/adapter/outbound/persistence/postgres"
	"go-judge-system/services/auth/internal/adapter/outbound/security"
	"go-judge-system/services/auth/internal/application/usecase"
	"go-judge-system/services/auth/internal/container"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*container.App, error) {
	databaseConfig := cfg.Database
	db, err := database.ConnectDatabase(databaseConfig)
	if err != nil {
		return nil, err
	}
	userRepository := postgres.NewUserRepository(db)
	passwordHasher := security.NewBcryptHasher()
	redisConfig := cfg.Redis
	client, err := cache.ConnectRedis(redisConfig)
	if err != nil {
		return nil, err
	}
	cacheRepository := redis.NewCacheRepository(client)
	smtpConfig := cfg.SMTP
	loggerConfig := cfg.Logger
	serverConfig := cfg.Server
	string2 := provideServerMode(serverConfig)
	zapLogger := logger.NewLogger(loggerConfig, string2)
	mailProvider := mail.NewSMTPProvider(smtpConfig, zapLogger)
	otpService := otp.NewOTPService(cacheRepository, mailProvider, zapLogger)
	registerUseCase := usecase.NewRegisterUseCase(userRepository, passwordHasher, otpService, zapLogger)
	registerHandler := handler.NewRegisterHandler(registerUseCase)
	verifyActivationUseCase := usecase.NewVerifyActivationUseCase(otpService, userRepository, zapLogger)
	verifyActivationHandler := handler.NewVerifyActivationHandler(verifyActivationUseCase)
	resendOTPUseCase := usecase.NewResendOTPUseCase(userRepository, otpService, zapLogger)
	resendOTPHandler := handler.NewResendOTPHandler(resendOTPUseCase)
	forgotPasswordUseCase := usecase.NewForgotPasswordUseCase(userRepository, otpService, zapLogger)
	forgotPasswordHandler := handler.NewForgotPasswordHandler(forgotPasswordUseCase)
	resetTokenRepository := redis.NewResetTokenRepository(client)
	resetTokenGenerator := crypto.NewResetTokenGenerator()
	verifyForgotPasswordUseCase := usecase.NewVerifyForgotPasswordUseCase(otpService, userRepository, resetTokenRepository, resetTokenGenerator, zapLogger)
	verifyForgotPasswordHandler := handler.NewVerifyForgotPasswordHandler(verifyForgotPasswordUseCase)
	resetPasswordUseCase := usecase.NewResetPasswordUseCase(userRepository, resetTokenRepository, resetTokenGenerator, passwordHasher, zapLogger)
	resetPasswordHandler := handler.NewResetPasswordHandler(resetPasswordUseCase)
	jwtConfig := cfg.JWT
	jwtProvider := jwt.NewJWTProvider(jwtConfig)
	loginUseCase := usecase.NewLoginUseCase(userRepository, passwordHasher, jwtProvider, zapLogger)
	loginHandler := handler.NewLoginHandler(loginUseCase)
	changePasswordUseCase := usecase.NewChangePasswordUseCase(userRepository, passwordHasher, zapLogger)
	changePasswordHandler := handler.NewChangePasswordHandler(changePasswordUseCase)
	logoutHandler := handler.NewLogoutHandler()
	refreshTokenUseCase := usecase.NewRefreshTokenUseCase(jwtProvider, zapLogger)
	refreshTokenHandler := handler.NewRefreshTokenHandler(refreshTokenUseCase)
	getProfileUseCase := usecase.NewGetProfileUseCase(userRepository, zapLogger)
	getProfileHandler := handler.NewGetProfileHandler(getProfileUseCase)
	authHandler := handler.NewAuthHandler(registerHandler, verifyActivationHandler, resendOTPHandler, forgotPasswordHandler, verifyForgotPasswordHandler, resetPasswordHandler, loginHandler, changePasswordHandler, logoutHandler, refreshTokenHandler, getProfileHandler)
	handlerFunc := middleware.NewAuthMiddleware(jwtProvider)
	router := http.NewRouter(authHandler, handlerFunc)
	app := container.NewApp(cfg, router, zapLogger)
	return app, nil
}

// wire.go:

func provideServerMode(cfg config.ServerConfig) string {
	return cfg.Mode
}
