package domain

import "go-judge-system/pkg/response"

var (
	ErrSubmissionNotFound          = response.NewAppError(response.CodeNotFound, "submission not found", nil)
	ErrSubmissionForbidden         = response.NewAppError(response.CodeForbidden, "you are not allowed to access this submission", nil)
	ErrInvalidSubmissionID         = response.NewAppError(response.CodeBadRequest, "invalid submission ID", nil)
	ErrSubmissionUnauthenticated   = response.NewAppError(response.CodeUnauthorized, "submission authentication required", nil)
	ErrInvalidProblemID            = response.NewAppError(response.CodeBadRequest, "invalid problem ID", nil)
	ErrInvalidUserID               = response.NewAppError(response.CodeBadRequest, "invalid user ID", nil)
	ErrProblemActorUnauthenticated = response.NewAppError(response.CodeUnauthorized, "problem actor authentication required", nil)
	ErrProblemActorForbidden       = response.NewAppError(response.CodeForbidden, "problem access forbidden", nil)
	ErrProblemNotFound             = response.NewAppError(response.CodeNotFound, "problem not found", nil)
	ErrProblemServiceUnavailable   = response.NewAppError(response.CodeServiceUnavailable, "problem service unavailable", nil)
	ErrInvalidLanguage             = response.NewAppError(response.CodeBadRequest, "invalid submission language", nil)
	ErrInvalidSourceCode           = response.NewAppError(response.CodeBadRequest, "invalid source code", nil)
	ErrSourceCodeTooLarge          = response.NewAppError(response.CodeBadRequest, "source code is too large", nil)
	ErrInvalidRunTestCase          = response.NewAppError(response.CodeBadRequest, "invalid run testcase", nil)
	ErrRunPayloadTooLarge          = response.NewAppError(response.CodePayloadTooLarge, "run payload is too large", nil)
	ErrUnsupportedRunLanguage      = response.NewAppError(response.CodeValidationFailed, "unsupported run language", nil)
	ErrJudgeWorkerUnavailable      = response.NewAppError(response.CodeServiceUnavailable, "judge worker unavailable", nil)
	ErrJudgeWorkerTimeout          = response.NewAppError(response.CodeGatewayTimeout, "judge worker timeout", nil)
	ErrInvalidSubmissionStatus     = response.NewAppError(response.CodeBadRequest, "invalid submission status", nil)
	ErrInvalidJudgeResult          = response.NewAppError(response.CodeBadRequest, "invalid judge result", nil)
	ErrInvalidPage                 = response.NewAppError(response.CodeBadRequest, "invalid page", nil)
	ErrInvalidLimit                = response.NewAppError(response.CodeBadRequest, "invalid limit", nil)
	ErrInvalidStatusTransition     = response.NewAppError(response.CodeConflict, "invalid submission status transition", nil)
	ErrInternalServer              = response.NewAppError(response.CodeInternalServer, "internal server error", nil)
)
