// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/auth/v1/user_internal.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolvePublicUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvePublicUserRequest) Reset() {
	*x = ResolvePublicUserRequest{}
	mi := &file_proto_auth_v1_user_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvePublicUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvePublicUserRequest) ProtoMessage() {}

func (x *ResolvePublicUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_user_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvePublicUserRequest.ProtoReflect.Descriptor instead.
func (*ResolvePublicUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_user_internal_proto_rawDescGZIP(), []int{0}
}

func (x *ResolvePublicUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ResolvePublicUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvePublicUserResponse) Reset() {
	*x = ResolvePublicUserResponse{}
	mi := &file_proto_auth_v1_user_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvePublicUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvePublicUserResponse) ProtoMessage() {}

func (x *ResolvePublicUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v1_user_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvePublicUserResponse.ProtoReflect.Descriptor instead.
func (*ResolvePublicUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_v1_user_internal_proto_rawDescGZIP(), []int{1}
}

func (x *ResolvePublicUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ResolvePublicUserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_proto_auth_v1_user_internal_proto protoreflect.FileDescriptor

const file_proto_auth_v1_user_internal_proto_rawDesc = "" +
	"\n" +
	"!proto/auth/v1/user_internal.proto\x12\aauth.v1\"6\n" +
	"\x18ResolvePublicUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"P\n" +
	"\x19ResolvePublicUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername2o\n" +
	"\x11PublicUserService\x12Z\n" +
	"\x11ResolvePublicUser\x12!.auth.v1.ResolvePublicUserRequest\x1a\".auth.v1.ResolvePublicUserResponseB'Z%go-judge-system/pkg/pb/auth/v1;authv1b\x06proto3"

var (
	file_proto_auth_v1_user_internal_proto_rawDescOnce sync.Once
	file_proto_auth_v1_user_internal_proto_rawDescData []byte
)

func file_proto_auth_v1_user_internal_proto_rawDescGZIP() []byte {
	file_proto_auth_v1_user_internal_proto_rawDescOnce.Do(func() {
		file_proto_auth_v1_user_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_v1_user_internal_proto_rawDesc), len(file_proto_auth_v1_user_internal_proto_rawDesc)))
	})
	return file_proto_auth_v1_user_internal_proto_rawDescData
}

var file_proto_auth_v1_user_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_auth_v1_user_internal_proto_goTypes = []any{
	(*ResolvePublicUserRequest)(nil),  // 0: auth.v1.ResolvePublicUserRequest
	(*ResolvePublicUserResponse)(nil), // 1: auth.v1.ResolvePublicUserResponse
}
var file_proto_auth_v1_user_internal_proto_depIdxs = []int32{
	0, // 0: auth.v1.PublicUserService.ResolvePublicUser:input_type -> auth.v1.ResolvePublicUserRequest
	1, // 1: auth.v1.PublicUserService.ResolvePublicUser:output_type -> auth.v1.ResolvePublicUserResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_auth_v1_user_internal_proto_init() }
func file_proto_auth_v1_user_internal_proto_init() {
	if File_proto_auth_v1_user_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_v1_user_internal_proto_rawDesc), len(file_proto_auth_v1_user_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_v1_user_internal_proto_goTypes,
		DependencyIndexes: file_proto_auth_v1_user_internal_proto_depIdxs,
		MessageInfos:      file_proto_auth_v1_user_internal_proto_msgTypes,
	}.Build()
	File_proto_auth_v1_user_internal_proto = out.File
	file_proto_auth_v1_user_internal_proto_goTypes = nil
	file_proto_auth_v1_user_internal_proto_depIdxs = nil
}
