// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/auth/v1/user_internal.proto

package authv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PublicUserService_ResolvePublicUser_FullMethodName = "/auth.v1.PublicUserService/ResolvePublicUser"
)

// PublicUserServiceClient is the client API for PublicUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PublicUserService exposes the minimum identity check needed by other
// services to safely serve public, user-owned data.
type PublicUserServiceClient interface {
	ResolvePublicUser(ctx context.Context, in *ResolvePublicUserRequest, opts ...grpc.CallOption) (*ResolvePublicUserResponse, error)
}

type publicUserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPublicUserServiceClient(cc grpc.ClientConnInterface) PublicUserServiceClient {
	return &publicUserServiceClient{cc}
}

func (c *publicUserServiceClient) ResolvePublicUser(ctx context.Context, in *ResolvePublicUserRequest, opts ...grpc.CallOption) (*ResolvePublicUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolvePublicUserResponse)
	err := c.cc.Invoke(ctx, PublicUserService_ResolvePublicUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicUserServiceServer is the server API for PublicUserService service.
// All implementations must embed UnimplementedPublicUserServiceServer
// for forward compatibility.
//
// PublicUserService exposes the minimum identity check needed by other
// services to safely serve public, user-owned data.
type PublicUserServiceServer interface {
	ResolvePublicUser(context.Context, *ResolvePublicUserRequest) (*ResolvePublicUserResponse, error)
	mustEmbedUnimplementedPublicUserServiceServer()
}

// UnimplementedPublicUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPublicUserServiceServer struct{}

func (UnimplementedPublicUserServiceServer) ResolvePublicUser(context.Context, *ResolvePublicUserRequest) (*ResolvePublicUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolvePublicUser not implemented")
}
func (UnimplementedPublicUserServiceServer) mustEmbedUnimplementedPublicUserServiceServer() {}
func (UnimplementedPublicUserServiceServer) testEmbeddedByValue()                           {}

// UnsafePublicUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublicUserServiceServer will
// result in compilation errors.
type UnsafePublicUserServiceServer interface {
	mustEmbedUnimplementedPublicUserServiceServer()
}

func RegisterPublicUserServiceServer(s grpc.ServiceRegistrar, srv PublicUserServiceServer) {
	// If the following call panics, it indicates UnimplementedPublicUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PublicUserService_ServiceDesc, srv)
}

func _PublicUserService_ResolvePublicUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolvePublicUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicUserServiceServer).ResolvePublicUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicUserService_ResolvePublicUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicUserServiceServer).ResolvePublicUser(ctx, req.(*ResolvePublicUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PublicUserService_ServiceDesc is the grpc.ServiceDesc for PublicUserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PublicUserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.v1.PublicUserService",
	HandlerType: (*PublicUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolvePublicUser",
			Handler:    _PublicUserService_ResolvePublicUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/auth/v1/user_internal.proto",
}
