package tags

// Definition is the immutable, canonical definition of one seed tag.
type Definition struct {
	Name        string
	Slug        string
	Description string
	Active      bool
}

func tag(name, slug, description string) Definition {
	return Definition{Name: name, Slug: slug, Description: description, Active: true}
}

// Desired returns a fresh copy of the curated Competitive Programming taxonomy.
func Desired() []Definition {
	return []Definition{
		// Fundamentals.
		tag("Implementation", "implementation", "Problems solved by carefully translating a specification into code."),
		tag("Simulation", "simulation", "Problems that model a process step by step according to stated rules."),
		tag("Brute Force", "brute-force", "Problems where trying every feasible candidate is sufficient within the limits."),
		tag("Complete Search", "complete-search", "Exhaustive exploration of a bounded search space with pruning when useful."),
		tag("Constructive Algorithms", "constructive-algorithms", "Problems that require building any object satisfying the requested constraints."),
		tag("Greedy", "greedy", "Problems solved by repeatedly making a locally optimal choice with a proof of correctness."),
		tag("Divide and Conquer", "divide-and-conquer", "Problems split into independent subproblems whose answers are combined."),
		tag("Recursion", "recursion", "Problems naturally expressed through self-referential subproblems or traversals."),
		tag("Backtracking", "backtracking", "Search problems that build candidates incrementally and undo invalid choices."),
		tag("Meet in the Middle", "meet-in-the-middle", "Problems accelerated by splitting an exponential search into two smaller halves."),
		tag("Two Pointers", "two-pointers", "Problems maintained with two moving positions over ordered data."),
		tag("Sliding Window", "sliding-window", "Problems solved by maintaining an aggregate over a moving contiguous range."),
		tag("Prefix Sum", "prefix-sum", "Problems using cumulative sums to answer range aggregate queries quickly."),
		tag("Difference Array", "difference-array", "Problems applying range updates through endpoint differences and reconstruction."),
		tag("Coordinate Compression", "coordinate-compression", "Problems replacing sparse values with compact order-preserving indices."),
		tag("Offline Queries", "offline-queries", "Queries reordered or processed together before individual answers are returned."),
		tag("Online Queries", "online-queries", "Queries that must be answered in arrival order using maintained state."),

		// Searching and sorting.
		tag("Sorting", "sorting", "Problems whose structure becomes simpler after ordering values or events."),
		tag("Binary Search", "binary-search", "Problems finding a boundary in a monotonic predicate or sorted sequence."),
		tag("Ternary Search", "ternary-search", "Problems locating an optimum of a unimodal discrete or continuous function."),
		tag("Quickselect", "quickselect", "Problems selecting an order statistic without fully sorting all values."),
		tag("Inversion Count", "inversion-count", "Problems counting out-of-order pairs, often with merge sort or a Fenwick tree."),

		// Data structures.
		tag("Array", "array", "Problems centered on indexed contiguous storage and range operations."),
		tag("Matrix", "matrix", "Problems operating on two-dimensional grids or tabular numeric data."),
		tag("String", "string", "Problems centered on sequences of characters and their transformations."),
		tag("Linked List", "linked-list", "Problems involving pointer-linked sequence operations."),
		tag("Stack", "stack", "Problems using last-in first-out state management."),
		tag("Queue", "queue", "Problems using first-in first-out processing."),
		tag("Deque", "deque", "Problems requiring efficient insertion and removal at both ends."),
		tag("Priority Queue", "priority-queue", "Problems repeatedly selecting the smallest or largest pending item."),
		tag("Heap", "heap", "Problems using heap-ordered data structures beyond simple priority queue operations."),
		tag("Hash Table", "hash-table", "Problems requiring expected constant-time key lookup or frequency counting."),
		tag("Set", "set", "Problems maintaining unique values and membership information."),
		tag("Map", "map", "Problems associating keys with values for lookup or aggregation."),
		tag("Bitset", "bitset", "Problems using packed boolean state and word-level bit operations."),
		tag("Sparse Table", "sparse-table", "Static range query problems solved by overlapping power-of-two intervals."),
		tag("Disjoint Set Union", "disjoint-set-union", "Problems maintaining connected components under merge operations."),
		tag("Fenwick Tree", "fenwick-tree", "Prefix aggregate and point or range update problems using a binary indexed tree."),
		tag("Segment Tree", "segment-tree", "Range query and update problems using a balanced interval tree."),
		tag("Lazy Segment Tree", "lazy-segment-tree", "Range update problems where segment tree updates are deferred with lazy propagation."),
		tag("Merge Sort Tree", "merge-sort-tree", "Range query problems using sorted values stored at segment tree nodes."),
		tag("Persistent Data Structure", "persistent-data-structure", "Problems retaining access to previous versions of a mutable data structure."),
		tag("Trie", "trie", "Problems indexing strings or sequences by shared prefixes."),
		tag("Binary Trie", "binary-trie", "Problems indexing integer bit representations for XOR or prefix operations."),
		tag("Sqrt Decomposition", "sqrt-decomposition", "Problems batching updates and queries into square-root sized blocks."),
		tag("Monotonic Stack", "monotonic-stack", "Problems maintaining a stack with monotonic values to find nearest boundaries."),
		tag("Monotonic Queue", "monotonic-queue", "Problems maintaining sliding extrema with a deque in monotonic order."),
		tag("Ordered Set", "ordered-set", "Problems requiring ordered membership, ranks, or predecessor and successor queries."),

		// Dynamic programming.
		tag("Dynamic Programming", "dynamic-programming", "Problems decomposed into overlapping subproblems with stored optimal results."),
		tag("Knapsack", "knapsack", "Selection problems constrained by capacity, cost, or total weight."),
		tag("Longest Increasing Subsequence", "longest-increasing-subsequence", "Problems finding or optimizing increasing subsequences."),
		tag("Longest Common Subsequence", "longest-common-subsequence", "Problems comparing sequences through their longest shared subsequence."),
		tag("Interval DP", "interval-dp", "Dynamic programming over contiguous intervals and split positions."),
		tag("Digit DP", "digit-dp", "Dynamic programming over the digits of a number, typically under numeric bounds."),
		tag("Bitmask DP", "bitmask-dp", "Dynamic programming whose state includes a subset represented by bits."),
		tag("Tree DP", "tree-dp", "Dynamic programming over rooted trees and subtree states."),
		tag("DAG DP", "dag-dp", "Dynamic programming over a directed acyclic graph in topological order."),
		tag("Probability DP", "probability-dp", "Dynamic programming that computes probabilities of events or states."),
		tag("DP Optimization", "dp-optimization", "Problems requiring a standard technique to reduce dynamic programming complexity."),
		tag("Divide and Conquer Optimization", "divide-and-conquer-optimization", "Dynamic programs optimized by monotonic optimal split positions."),
		tag("Knuth Optimization", "knuth-optimization", "Interval dynamic programs optimized by Knuth's quadrangle inequality conditions."),
		tag("Convex Hull Trick", "convex-hull-trick", "Dynamic programs optimized by queries against a set of affine functions."),
		tag("Sum Over Subsets DP", "sum-over-subsets-dp", "Subset dynamic programming accelerated by iterating over submasks or supermasks."),

		// Graph theory and trees.
		tag("Graph", "graph", "Problems modeled with vertices and edges."),
		tag("Graph Traversal", "graph-traversal", "Problems exploring graph reachability or visit order."),
		tag("Breadth First Search", "breadth-first-search", "Unweighted shortest-path and layer-by-layer graph exploration problems."),
		tag("Depth First Search", "depth-first-search", "Graph or tree exploration problems using depth-first ordering."),
		tag("Connected Components", "connected-components", "Problems identifying groups of mutually reachable vertices."),
		tag("Flood Fill", "flood-fill", "Grid or graph component problems expanding from a starting cell or vertex."),
		tag("Topological Sort", "topological-sort", "Dependency ordering problems on directed acyclic graphs."),
		tag("Directed Acyclic Graph", "directed-acyclic-graph", "Problems exploiting the properties of a graph without directed cycles."),
		tag("Shortest Path", "shortest-path", "Problems finding minimum-cost routes through weighted or unweighted graphs."),
		tag("Dijkstra", "dijkstra", "Shortest-path problems on graphs with non-negative edge weights."),
		tag("Bellman Ford", "bellman-ford", "Shortest-path problems with negative edges or negative-cycle detection."),
		tag("Floyd Warshall", "floyd-warshall", "All-pairs shortest-path problems on small dense graphs."),
		tag("0-1 BFS", "zero-one-bfs", "Shortest-path problems whose edge weights are only zero or one."),
		tag("Minimum Spanning Tree", "minimum-spanning-tree", "Problems connecting all vertices with minimum total edge cost."),
		tag("Kruskal", "kruskal", "Minimum spanning tree problems solved by sorting edges and using disjoint sets."),
		tag("Prim", "prim", "Minimum spanning tree problems grown from a frontier using a priority queue."),
		tag("Strongly Connected Components", "strongly-connected-components", "Problems partitioning directed graphs into mutually reachable components."),
		tag("Tarjan", "tarjan", "Graph decomposition problems using low-link values and depth-first search."),
		tag("Kosaraju", "kosaraju", "Strongly connected component problems using two depth-first search passes."),
		tag("Bridges", "bridges", "Problems identifying edges whose removal disconnects an undirected graph."),
		tag("Articulation Points", "articulation-points", "Problems identifying vertices whose removal disconnects an undirected graph."),
		tag("Biconnected Components", "biconnected-components", "Problems decomposing undirected graphs by articulation structure."),
		tag("Euler Tour", "euler-tour", "Problems using an entry and exit traversal ordering to represent tree substructures."),
		tag("Eulerian Path", "eulerian-path", "Problems finding a path that uses every edge exactly once."),
		tag("Hamiltonian Path", "hamiltonian-path", "Problems finding a path that visits every vertex exactly once."),
		tag("Bipartite Graph", "bipartite-graph", "Problems involving two-colorable graphs or two disjoint vertex sets."),
		tag("Bipartite Matching", "bipartite-matching", "Problems pairing vertices across two sets under compatibility constraints."),
		tag("Maximum Flow", "maximum-flow", "Network problems maximizing transferable capacity from source to sink."),
		tag("Minimum Cut", "minimum-cut", "Network problems minimizing the capacity needed to separate source and sink."),
		tag("Min Cost Max Flow", "min-cost-max-flow", "Flow problems optimizing cost while sending as much flow as required."),
		tag("Network Flow", "network-flow", "Problems modeled with capacities, conservation, and flows through a network."),
		tag("Functional Graph", "functional-graph", "Problems on directed graphs where every vertex has exactly one outgoing edge."),
		tag("Graph Coloring", "graph-coloring", "Problems assigning colors to vertices subject to adjacency constraints."),
		tag("Heavy Light Decomposition", "heavy-light-decomposition", "Tree path query problems decomposed into logarithmically many chains."),
		tag("Centroid Decomposition", "centroid-decomposition", "Tree problems recursively decomposed around balanced centroid vertices."),
		tag("Small to Large Merging", "small-to-large-merging", "Problems merging smaller collections into larger ones to bound total work."),
		tag("Tree", "tree", "Problems modeled by connected acyclic graphs."),
		tag("Binary Tree", "binary-tree", "Problems involving trees where each node has at most two children."),
		tag("Binary Search Tree", "binary-search-tree", "Problems using ordered binary tree structure and search invariants."),
		tag("Tree Traversal", "tree-traversal", "Problems requiring preorder, inorder, postorder, or level traversal of trees."),
		tag("Lowest Common Ancestor", "lowest-common-ancestor", "Tree query problems finding the deepest shared ancestor of two nodes."),
		tag("Binary Lifting", "binary-lifting", "Ancestor or jump query problems using powers-of-two transition tables."),
		tag("Subtree Queries", "subtree-queries", "Tree problems answering or updating values over a node's subtree."),
		tag("Tree Diameter", "tree-diameter", "Problems finding the longest path between two vertices in a tree."),
		tag("Tree Flattening", "tree-flattening", "Tree problems mapped to an array interval through traversal order."),
		tag("Rerooting", "rerooting", "Tree dynamic programming that efficiently computes answers for every possible root."),
		tag("DSU on Tree", "dsu-on-tree", "Subtree query problems using small-to-large frequency merging during DFS."),

		// Mathematics.
		tag("Mathematics", "mathematics", "Problems whose key ideas are mathematical identities, proofs, or transformations."),
		tag("Number Theory", "number-theory", "Problems involving integer divisibility, primes, and arithmetic structure."),
		tag("Arithmetic", "arithmetic", "Problems using direct integer or real-number calculations."),
		tag("Modular Arithmetic", "modular-arithmetic", "Problems performing calculations modulo a fixed integer."),
		tag("Modular Inverse", "modular-inverse", "Problems requiring multiplicative inverses under modular arithmetic."),
		tag("Greatest Common Divisor", "greatest-common-divisor", "Problems using common divisors and Euclid's algorithm."),
		tag("Least Common Multiple", "least-common-multiple", "Problems using common multiples or factor exponent aggregation."),
		tag("Prime Numbers", "prime-numbers", "Problems testing, generating, or reasoning about prime numbers."),
		tag("Sieve of Eratosthenes", "sieve-of-eratosthenes", "Problems generating primes or divisor information over a bounded range."),
		tag("Prime Factorization", "prime-factorization", "Problems decomposing integers into prime factors and their exponents."),
		tag("Divisors", "divisors", "Problems enumerating, counting, or optimizing over divisors."),
		tag("Euler Totient", "euler-totient", "Problems using the count of integers coprime to a given number."),
		tag("Chinese Remainder Theorem", "chinese-remainder-theorem", "Problems combining compatible modular congruences."),
		tag("Diophantine Equations", "diophantine-equations", "Problems solving integer equations under arithmetic constraints."),
		tag("Extended Euclidean Algorithm", "extended-euclidean-algorithm", "Problems computing Bezout coefficients, gcds, or modular inverses."),
		tag("Fast Exponentiation", "fast-exponentiation", "Problems computing powers quickly by repeated squaring."),
		tag("Combinatorics", "combinatorics", "Problems counting arrangements, selections, and discrete structures."),
		tag("Permutations", "permutations", "Problems involving orderings of distinct or repeated elements."),
		tag("Combinations", "combinations", "Problems selecting subsets without regard to order."),
		tag("Binomial Coefficients", "binomial-coefficients", "Problems computing or applying choose values."),
		tag("Inclusion Exclusion", "inclusion-exclusion", "Counting problems corrected by alternating overlaps of sets."),
		tag("Pigeonhole Principle", "pigeonhole-principle", "Existence problems proved by placing more objects than available categories."),
		tag("Catalan Numbers", "catalan-numbers", "Counting problems involving balanced structures such as parentheses or tree shapes."),
		tag("Fibonacci", "fibonacci", "Problems using Fibonacci recurrence properties or identities."),
		tag("Matrix Exponentiation", "matrix-exponentiation", "Linear recurrence problems accelerated by exponentiating transition matrices."),
		tag("Linear Algebra", "linear-algebra", "Problems modeled with vectors, matrices, and linear transformations."),
		tag("Gaussian Elimination", "gaussian-elimination", "Problems solving systems of linear equations by row reduction."),
		tag("Probability", "probability", "Problems computing likelihoods of random events."),
		tag("Expected Value", "expected-value", "Problems computing the average outcome of a random process."),
		tag("Game Theory", "game-theory", "Problems analyzing optimal play between competing participants."),
		tag("Nim", "nim", "Impartial game problems reducible to Nim heaps and XOR."),
		tag("Sprague Grundy", "sprague-grundy", "Impartial game problems combined through Grundy values and XOR."),
		tag("Grundy Numbers", "grundy-numbers", "Game problems computing the mex-based value of impartial positions."),

		// Strings.
		tag("String Algorithms", "string-algorithms", "Problems requiring specialized algorithms over character sequences."),
		tag("String Matching", "string-matching", "Problems finding occurrences or alignments of patterns in text."),
		tag("Prefix Function", "prefix-function", "String problems using longest proper prefix and suffix information."),
		tag("Knuth Morris Pratt", "knuth-morris-pratt", "Pattern matching problems solved with the prefix function."),
		tag("Z Function", "z-function", "String problems using prefix match lengths at every position."),
		tag("Rolling Hash", "rolling-hash", "Substring comparison problems using efficiently updated hash values."),
		tag("String Hashing", "string-hashing", "Problems representing strings with hashes for comparison or lookup."),
		tag("Rabin Karp", "rabin-karp", "Pattern matching problems using rolling hashes."),
		tag("Aho Corasick", "aho-corasick", "Multi-pattern matching problems using a trie automaton with failure links."),
		tag("Suffix Array", "suffix-array", "String ordering and substring query problems using sorted suffixes."),
		tag("Suffix Automaton", "suffix-automaton", "Substring counting and occurrence problems using a suffix state machine."),
		tag("Suffix Tree", "suffix-tree", "Substring query problems using a compressed suffix trie."),
		tag("Longest Common Prefix", "longest-common-prefix", "Problems comparing adjacent suffixes or strings by their shared prefixes."),
		tag("Manacher", "manacher", "Palindrome radius problems solved in linear time."),
		tag("Palindrome", "palindrome", "Problems involving strings or sequences equal to their reverse."),

		// Geometry.
		tag("Geometry", "geometry", "Problems modeled with geometric objects and spatial relationships."),
		tag("Computational Geometry", "computational-geometry", "Problems requiring algorithmic operations on geometric primitives."),
		tag("Point", "point", "Problems centered on coordinates and point relationships."),
		tag("Vector", "vector", "Problems using direction, displacement, dot products, or cross products."),
		tag("Line", "line", "Problems involving infinite lines and their equations."),
		tag("Segment", "segment", "Problems involving finite line segments and their relationships."),
		tag("Circle", "circle", "Problems involving circular geometry and distances from centers."),
		tag("Polygon", "polygon", "Problems operating on closed planar shapes defined by vertices."),
		tag("Convex Hull", "convex-hull", "Problems finding or using the smallest convex polygon containing points."),
		tag("Point in Polygon", "point-in-polygon", "Problems deciding whether points lie inside, outside, or on a polygon."),
		tag("Line Intersection", "line-intersection", "Problems computing or testing intersections of infinite lines."),
		tag("Segment Intersection", "segment-intersection", "Problems computing or testing intersections of finite line segments."),
		tag("Sweep Line", "sweep-line", "Problems processed by moving an ordered event line across geometric data."),
		tag("Closest Pair", "closest-pair", "Problems finding the pair of points with minimum distance."),
		tag("Rotating Calipers", "rotating-calipers", "Convex polygon problems optimized by advancing antipodal pointers."),
		tag("Pick's Theorem", "picks-theorem", "Lattice polygon problems relating area, boundary points, and interior points."),

		// Bit manipulation.
		tag("Bit Manipulation", "bit-manipulation", "Problems using binary representation and bitwise operations."),
		tag("Bitmask", "bitmask", "Problems representing subsets or compact state with integer bits."),
		tag("Bitmask Enumeration", "bitmask-enumeration", "Problems iterating through masks representing subsets or configurations."),
		tag("Submask Enumeration", "submask-enumeration", "Problems efficiently iterating through all submasks of a mask."),
		tag("XOR", "xor", "Problems using exclusive-or algebra and binary parity properties."),
		tag("XOR Basis", "xor-basis", "Problems maintaining a linear basis over binary vectors for XOR optimization."),
		tag("Gray Code", "gray-code", "Problems using sequences where adjacent bit patterns differ in one bit."),

		// Advanced algorithms.
		tag("Randomized Algorithms", "randomized-algorithms", "Problems using randomness to simplify construction, search, or expected complexity."),
		tag("Mo's Algorithm", "mos-algorithm", "Offline range query problems reordered to minimize pointer movement."),
		tag("Parallel Binary Search", "parallel-binary-search", "Batch decision problems solved by sharing binary-search iterations."),
		tag("Fractional Cascading", "fractional-cascading", "Related search queries accelerated by linking sorted catalogs."),
		tag("Persistent Segment Tree", "persistent-segment-tree", "Versioned range query problems using persistent segment tree nodes."),
		tag("Li Chao Tree", "li-chao-tree", "Line query problems maintaining affine functions over a coordinate domain."),
		tag("Treap", "treap", "Problems using randomized balanced binary search trees."),
		tag("Splay Tree", "splay-tree", "Problems using self-adjusting binary search trees with amortized guarantees."),
		tag("Cartesian Tree", "cartesian-tree", "Problems building a tree that combines sequence order with heap order."),
		tag("Link Cut Tree", "link-cut-tree", "Dynamic tree problems supporting path operations and link or cut updates."),
		tag("Euler Tour Tree", "euler-tour-tree", "Dynamic forest problems represented through Euler traversal sequences."),
		tag("Fast Fourier Transform", "fast-fourier-transform", "Polynomial or convolution problems accelerated in the frequency domain."),
		tag("Number Theoretic Transform", "number-theoretic-transform", "Modular convolution problems using roots of unity in finite fields."),
		tag("Polynomial", "polynomial", "Problems manipulating polynomial representations and operations."),
		tag("Convolution", "convolution", "Problems combining sequences through pairwise index sums."),
		tag("Fast Multipoint Evaluation", "fast-multipoint-evaluation", "Problems evaluating a polynomial at many points faster than one-by-one evaluation."),

		// Problem styles and common techniques.
		tag("Ad Hoc", "ad-hoc", "Problems solved primarily through problem-specific observations."),
		tag("Interactive", "interactive", "Problems where the program exchanges queries and responses with a judge."),
		tag("Output Only", "output-only", "Problems evaluated from a produced construction without standard input interaction."),
		tag("Queries", "queries", "Problems centered on answering multiple requests over changing or static data."),
		tag("Range Queries", "range-queries", "Problems answering aggregate questions over intervals or subarrays."),
		tag("Range Updates", "range-updates", "Problems applying modifications across contiguous ranges."),
		tag("Offline", "offline", "Problems whose operations can be reordered or processed after all input is known."),
		tag("Online", "online", "Problems whose operations must be handled as they arrive."),
		tag("Optimization", "optimization", "Problems asking for the best value under stated constraints."),
		tag("Counting", "counting", "Problems asking for the number of valid objects or configurations."),
		tag("Enumeration", "enumeration", "Problems requiring generation or traversal of all relevant candidates."),
		tag("Parsing", "parsing", "Problems requiring structured interpretation of input text or expressions."),
	}
}
